"""migration 06

Revision ID: 4e53c3e3a6a2
Revises: 23c8f6d38f4a
Create Date: 2024-07-19 18:40:17.469627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e53c3e3a6a2'
down_revision: Union[str, None] = '23c8f6d38f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_brand', table_name='items')
    op.drop_index('ix_items_price', table_name='items')
    op.drop_column('items', 'brand')
    op.drop_column('items', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('price', sa.INTEGER(), nullable=True))
    op.add_column('items', sa.Column('brand', sa.INTEGER(), nullable=True))
    op.create_index('ix_items_price', 'items', ['price'], unique=False)
    op.create_index('ix_items_brand', 'items', ['brand'], unique=False)
    # ### end Alembic commands ###
