"""migration 03

Revision ID: 599495d89db7
Revises: fbc17963132f
Create Date: 2024-07-19 18:19:13.637296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '599495d89db7'
down_revision: Union[str, None] = 'fbc17963132f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_price', table_name='items')
    op.drop_column('items', 'brand')
    op.drop_column('items', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('price', sa.INTEGER(), nullable=True))
    op.add_column('items', sa.Column('brand', sa.VARCHAR(), nullable=True))
    op.create_index('ix_items_price', 'items', ['price'], unique=False)
    # ### end Alembic commands ###
