"""migration 01

Revision ID: 71f92ed530f8
Revises: 43147a257094
Create Date: 2024-07-19 18:07:34.401984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71f92ed530f8'
down_revision: Union[str, None] = '43147a257094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('price', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_items_price'), 'items', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_price'), table_name='items')
    op.drop_column('items', 'price')
    # ### end Alembic commands ###
