"""adding price and brand columns. removing age column

Revision ID: 8012a6828ddd
Revises: 3f3a2be81166
Create Date: 2024-07-22 16:22:04.740439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8012a6828ddd'
down_revision: Union[str, None] = '3f3a2be81166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('items', 'brand',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.String(),
    #            existing_nullable=True)
    op.drop_index('ix_items_age', table_name='items')
    op.drop_column('items', 'age')
    op.drop_index('ix_items_brand', table_name='items')
    op.drop_column('items', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ##
    # ### end Alembic commands ###
    pass
