"""column updates

Revision ID: 8683b9b4d7f5
Revises: 8012a6828ddd
Create Date: 2024-07-22 16:32:06.136508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8683b9b4d7f5'
down_revision: Union[str, None] = '8012a6828ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('item_name', sa.String(), nullable=True))
    op.add_column('items', sa.Column('brand_name', sa.String(), nullable=True))
    op.drop_index('ix_items_name', table_name='items')
    op.create_index(op.f('ix_items_brand_name'), 'items', ['brand_name'], unique=False)
    op.create_index(op.f('ix_items_item_name'), 'items', ['item_name'], unique=False)
    op.drop_column('items', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_items_item_name'), table_name='items')
    op.drop_index(op.f('ix_items_brand_name'), table_name='items')
    op.create_index('ix_items_name', 'items', ['name'], unique=False)
    op.drop_column('items', 'brand_name')
    op.drop_column('items', 'item_name')
    # ### end Alembic commands ###
