"""migration 06

Revision ID: fcf7593c5ff7
Revises: 5ce9e7c4123e
Create Date: 2024-07-19 18:46:18.451032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf7593c5ff7'
down_revision: Union[str, None] = '5ce9e7c4123e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_brand', table_name='items')
    op.drop_index('ix_items_price', table_name='items')
    op.drop_column('items', 'brand')
    op.drop_column('items', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('price', sa.INTEGER(), nullable=True))
    op.add_column('items', sa.Column('brand', sa.INTEGER(), nullable=True))
    op.create_index('ix_items_price', 'items', ['price'], unique=False)
    op.create_index('ix_items_brand', 'items', ['brand'], unique=False)
    # ### end Alembic commands ###
